version: '3'

tasks:
  default:
    cmds:
      - task: release

  prep:
    internal: true
    cmds:
      - powershell -Command "if (!(Test-Path build)) { New-Item -ItemType Directory -Path build }"
      - echo "Compiling DLL"
      - cl /nologo /LD /EHsc /std:c++17 cpp/media.cpp windowsapp.lib /Fobuild/ /link /out:build/media.dll

  debug:
    desc: "Build with terminal for debugging"
    deps: [prep]
    cmds:
      - go build -o build/scrobbler_debug.exe main.go

  release:
    desc: "Build for release (No terminal, with Icon)"
    deps: [prep]
    cmds:
      - go build -ldflags="-H windowsgui -s -w" -o build/scrobbler.exe main.go